### ISSUE TITLE
convert from PropertySet to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/protein-synthesis#26]
PropertySet is deprecated and should be replaced by Property, see phetsims/axon#102. Since this sim hasn't been published yet, this should be done before RC testing and publishing.

**Comment by zepumph** [comment]
In https://github.com/phetsims/axon/issues/102#issuecomment-310259248 I see that @samreid has finished this issue over there. The the commits are above that comment in that issue. Closing
